agent:
  name: "syswatch-pro"
  interval_seconds: 60

logging:
  level: "INFO"
  file: "syswatch.log"

aws:
  region_name: "ap-southeast-1"
  namespace: "syswatch-pro"  # CloudWatch custom namespace
  dimensions:
    - Name: "InstanceId"
      Value: "local-dev"   # Later on EC2, we'll set this to the real instance ID
